### ISSUE TITLE
feat: completion models unit tests and integration tests

### ISSUE THREAD

**Issue by garance-buricatu** [0xPlaygrounds/rig#96] opened 2024-11-11 16:16 UTC
- [x] I have looked for existing issues (including closed) about this

## Feature Request
* Create testing matrix for all completion model providers
EX: with/out additional params, with/out tools, ...

* integration tests

Research
* https://rust.testcontainers.org

**Comment by mateobelanger** [comment] 2024-11-12 16:05
Duplicate of #68. Will close

**Closed by mateobelanger** 2024-11-12 16:05 UTC
Labels: CI/CD, test
